/**
 * The background soundscapes offered during a meditation, breathing or reading
 * session — names, ids and levels only.
 *
 * The audio files themselves live in `soundscapeAssets.ts`, because loading one
 * is a `require` of a .wav, which is a Metro bundler feature and not something
 * Node can evaluate. Keeping the two apart is what lets this half be tested.
 *
 * The tracks are synthesised loops, generated by `tools/make-ambience.mjs`.
 * Noise is what synthesis does honestly — brown noise and rain are the real
 * thing, since the real thing *is* filtered noise. Waves and embers are
 * approximations, and a field recording would beat both. Swapping one out is a
 * change to the asset file and nothing else.
 */

export type SoundscapeId = 'brown' | 'rain' | 'waves' | 'embers' | 'drone';

export type Soundscape = { id: SoundscapeId; name: string };

export const SOUNDSCAPES: Soundscape[] = [
  { id: 'brown', name: 'Brown noise' },
  { id: 'rain', name: 'Rain' },
  { id: 'waves', name: 'Waves' },
  { id: 'embers', name: 'Embers' },
  { id: 'drone', name: 'Warm drone' },
];

/** The value the picker uses for "no soundscape". Never a track id. */
export const SOUND_OFF = 'off';

export function soundscapeById(id: string): Soundscape | undefined {
  return SOUNDSCAPES.find((track) => track.id === id);
}

/** Assets are named by convention, which `soundscapes.test.ts` enforces. */
export function soundscapeFileName(id: SoundscapeId): string {
  return `amb-${id}.wav`;
}

export type VolumeLevel = 'low' | 'medium' | 'high';

export const VOLUME_LEVELS: { id: VolumeLevel; name: string }[] = [
  { id: 'low', name: 'Low' },
  { id: 'medium', name: 'Medium' },
  { id: 'high', name: 'High' },
];

/**
 * Three steps rather than a slider: no extra dependency, a much bigger target
 * in the dark, and nobody has ever needed 43% of a rain loop.
 *
 * All three are quiet in absolute terms. This plays in a silent room next to
 * someone's head, and the loudest setting still has to sit under a bell.
 */
const GAINS: Record<VolumeLevel, number> = {
  low: 0.18,
  medium: 0.38,
  high: 0.65,
};

export function gainFor(level: VolumeLevel): number {
  return GAINS[level];
}
